# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.service_order_item_measurements_api import ServiceOrderItemMeasurementsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceOrderItemMeasurementsApi(unittest.TestCase):
    """ServiceOrderItemMeasurementsApi unit test stubs"""

    def setUp(self):
        self.api = ServiceOrderItemMeasurementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service_order_item_measurements_add_auxiliary_tools(self):
        """Test case for service_order_item_measurements_add_auxiliary_tools

        """
        pass

    def test_service_order_item_measurements_create_measurement_form(self):
        """Test case for service_order_item_measurements_create_measurement_form

        Create Measurement Form.  # noqa: E501
        """
        pass

    def test_service_order_item_measurements_get_measurement_form(self):
        """Test case for service_order_item_measurements_get_measurement_form

        Get Measurement Form.  # noqa: E501
        """
        pass

    def test_service_order_item_measurements_get_measurements_by_asset(self):
        """Test case for service_order_item_measurements_get_measurements_by_asset

        """
        pass

    def test_service_order_item_measurements_update_measurement_form(self):
        """Test case for service_order_item_measurements_update_measurement_form

        Update Measurement Form.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
