# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qualer_sdk
from qualer_sdk.api.service_order_payments_api import ServiceOrderPaymentsApi  # noqa: E501
from qualer_sdk.rest import ApiException


class TestServiceOrderPaymentsApi(unittest.TestCase):
    """ServiceOrderPaymentsApi unit test stubs"""

    def setUp(self):
        self.api = ServiceOrderPaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service_order_payments_change_work_order_payment_status(self):
        """Test case for service_order_payments_change_work_order_payment_status

        """
        pass

    def test_service_order_payments_create_work_order_payment(self):
        """Test case for service_order_payments_create_work_order_payment

        """
        pass

    def test_service_order_payments_get_all_work_order_payments(self):
        """Test case for service_order_payments_get_all_work_order_payments

        """
        pass

    def test_service_order_payments_get_work_order_payment(self):
        """Test case for service_order_payments_get_work_order_payment

        """
        pass


if __name__ == '__main__':
    unittest.main()
