# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.client_asset_attributes_api import ClientAssetAttributesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientAssetAttributesApi(unittest.TestCase):
    """ClientAssetAttributesApi unit test stubs"""

    def setUp(self):
        self.api = ClientAssetAttributesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_client_asset_attributes_get_asset_attributes(self):
        """Test case for client_asset_attributes_get_asset_attributes

        """
        pass

    def test_client_asset_attributes_upsert_asset_attributes(self):
        """Test case for client_asset_attributes_upsert_asset_attributes

        """
        pass


if __name__ == '__main__':
    unittest.main()
