# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qualer_sdk
from qualer_sdk.api.service_order_items_api import ServiceOrderItemsApi  # noqa: E501
from qualer_sdk.rest import ApiException


class TestServiceOrderItemsApi(unittest.TestCase):
    """ServiceOrderItemsApi unit test stubs"""

    def setUp(self):
        self.api = ServiceOrderItemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service_order_items_add_work_items(self):
        """Test case for service_order_items_add_work_items

        Add work items  # noqa: E501
        """
        pass

    def test_service_order_items_delete_work_item_image(self):
        """Test case for service_order_items_delete_work_item_image

        """
        pass

    def test_service_order_items_get_work_item(self):
        """Test case for service_order_items_get_work_item

        """
        pass

    def test_service_order_items_get_work_item_charges(self):
        """Test case for service_order_items_get_work_item_charges

        """
        pass

    def test_service_order_items_get_work_item_image(self):
        """Test case for service_order_items_get_work_item_image

        """
        pass

    def test_service_order_items_get_work_item_images(self):
        """Test case for service_order_items_get_work_item_images

        """
        pass

    def test_service_order_items_get_work_items(self):
        """Test case for service_order_items_get_work_items

        """
        pass

    def test_service_order_items_get_work_items_0(self):
        """Test case for service_order_items_get_work_items_0

        Retrieve work items  # noqa: E501
        """
        pass

    def test_service_order_items_put_charges(self):
        """Test case for service_order_items_put_charges

        Apply Service Order Item Charges  # noqa: E501
        """
        pass

    def test_service_order_items_set_work_item(self):
        """Test case for service_order_items_set_work_item

        Update work item  # noqa: E501
        """
        pass

    def test_service_order_items_upload_work_item_images(self):
        """Test case for service_order_items_upload_work_item_images

        """
        pass


if __name__ == '__main__':
    unittest.main()
