# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qualer_sdk
from qualer_sdk.models.qualer_api_models_vendors_to_created_vendor_company_response import QualerApiModelsVendorsToCreatedVendorCompanyResponse  # noqa: E501
from qualer_sdk.rest import ApiException


class TestQualerApiModelsVendorsToCreatedVendorCompanyResponse(unittest.TestCase):
    """QualerApiModelsVendorsToCreatedVendorCompanyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQualerApiModelsVendorsToCreatedVendorCompanyResponse(self):
        """Test QualerApiModelsVendorsToCreatedVendorCompanyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.qualer_api_models_vendors_to_created_vendor_company_response.QualerApiModelsVendorsToCreatedVendorCompanyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
