# coding: utf-8

"""
Qualer.Web.Mvc

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import qualer_sdk
from qualer_sdk.models.qualer_web_mvc_areas_api_models_company_from_add_department_model import (
    QualerWebMvcAreasApiModelsCompanyFromAddDepartmentModel,
)  # noqa: E501
from qualer_sdk.rest import ApiException


class TestQualerWebMvcAreasApiModelsCompanyFromAddDepartmentModel(unittest.TestCase):
    """QualerWebMvcAreasApiModelsCompanyFromAddDepartmentModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQualerWebMvcAreasApiModelsCompanyFromAddDepartmentModel(self):
        """Test QualerWebMvcAreasApiModelsCompanyFromAddDepartmentModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qualer_sdk.models.qualer_web_mvc_areas_api_models_company_from_add_department_model.QualerWebMvcAreasApiModelsCompanyFromAddDepartmentModel()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
