# coding: utf-8

"""
Qualer.Web.Mvc

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import qualer_sdk
from qualer_sdk.models.qualer_api_models_measurements_to_measurement_record_response_model_measurement_batch_response_model import (
    QualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModel,
)  # noqa: E501
from qualer_sdk.rest import ApiException


class TestQualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModel(
    unittest.TestCase
):
    """QualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModel(
        self,
    ):
        """Test QualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qualer_sdk.models.qualer_api_models_measurements_to_measurement_record_response_model_measurement_batch_response_model.QualerApiModelsMeasurementsToMeasurementRecordResponseModelMeasurementBatchResponseModel()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
