# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.qualer_api_models_account_from_employee_messages_model import QualerApiModelsAccountFromEmployeeMessagesModel  # noqa: E501
from swagger_client.rest import ApiException


class TestQualerApiModelsAccountFromEmployeeMessagesModel(unittest.TestCase):
    """QualerApiModelsAccountFromEmployeeMessagesModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQualerApiModelsAccountFromEmployeeMessagesModel(self):
        """Test QualerApiModelsAccountFromEmployeeMessagesModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.qualer_api_models_account_from_employee_messages_model.QualerApiModelsAccountFromEmployeeMessagesModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
