# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import qualer_sdk
from qualer_sdk.api.account_api import AccountApi  # noqa: E501
from qualer_sdk.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = qualer_sdk.api.account_api.AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies(self):
        """Test case for companies

        """
        pass

    def test_get_employee_message(self):
        """Test case for get_employee_message

        """
        pass

    def test_get_employee_messages(self):
        """Test case for get_employee_messages

        """
        pass

    def test_login(self):
        """Test case for login

        Login  # noqa: E501
        """
        pass

    def test_logout(self):
        """Test case for logout

        Logout  # noqa: E501
        """
        pass

    def test_post_employee_location(self):
        """Test case for post_employee_location

        Post Employee Location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
