# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'task_name': 'str',
        'task_details': 'str',
        'start_time': 'datetime',
        'finish_time': 'datetime',
        'time_spent_minutes': 'int',
        'price': 'float',
        'is_hourly': 'bool'
    }

    attribute_map = {
        'task_name': 'TaskName',
        'task_details': 'TaskDetails',
        'start_time': 'StartTime',
        'finish_time': 'FinishTime',
        'time_spent_minutes': 'TimeSpentMinutes',
        'price': 'Price',
        'is_hourly': 'IsHourly'
    }

    def __init__(self, task_name=None, task_details=None, start_time=None, finish_time=None, time_spent_minutes=None, price=None, is_hourly=None, _configuration=None):  # noqa: E501
        """QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._task_name = None
        self._task_details = None
        self._start_time = None
        self._finish_time = None
        self._time_spent_minutes = None
        self._price = None
        self._is_hourly = None
        self.discriminator = None

        if task_name is not None:
            self.task_name = task_name
        if task_details is not None:
            self.task_details = task_details
        if start_time is not None:
            self.start_time = start_time
        if finish_time is not None:
            self.finish_time = finish_time
        if time_spent_minutes is not None:
            self.time_spent_minutes = time_spent_minutes
        if price is not None:
            self.price = price
        if is_hourly is not None:
            self.is_hourly = is_hourly

    @property
    def task_name(self):
        """Gets the task_name of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501


        :return: The task_name of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :rtype: str
        """
        return self._task_name

    @task_name.setter
    def task_name(self, task_name):
        """Sets the task_name of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.


        :param task_name: The task_name of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :type: str
        """

        self._task_name = task_name

    @property
    def task_details(self):
        """Gets the task_details of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501


        :return: The task_details of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :rtype: str
        """
        return self._task_details

    @task_details.setter
    def task_details(self, task_details):
        """Sets the task_details of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.


        :param task_details: The task_details of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :type: str
        """

        self._task_details = task_details

    @property
    def start_time(self):
        """Gets the start_time of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501


        :return: The start_time of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.


        :param start_time: The start_time of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def finish_time(self):
        """Gets the finish_time of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501


        :return: The finish_time of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :rtype: datetime
        """
        return self._finish_time

    @finish_time.setter
    def finish_time(self, finish_time):
        """Sets the finish_time of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.


        :param finish_time: The finish_time of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :type: datetime
        """

        self._finish_time = finish_time

    @property
    def time_spent_minutes(self):
        """Gets the time_spent_minutes of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501


        :return: The time_spent_minutes of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :rtype: int
        """
        return self._time_spent_minutes

    @time_spent_minutes.setter
    def time_spent_minutes(self, time_spent_minutes):
        """Sets the time_spent_minutes of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.


        :param time_spent_minutes: The time_spent_minutes of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :type: int
        """

        self._time_spent_minutes = time_spent_minutes

    @property
    def price(self):
        """Gets the price of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501


        :return: The price of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.


        :param price: The price of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def is_hourly(self):
        """Gets the is_hourly of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501


        :return: The is_hourly of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :rtype: bool
        """
        return self._is_hourly

    @is_hourly.setter
    def is_hourly(self, is_hourly):
        """Sets the is_hourly of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.


        :param is_hourly: The is_hourly of this QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel.  # noqa: E501
        :type: bool
        """

        self._is_hourly = is_hourly

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, QualerApiModelsServiceOrdersFromServiceOrderTaskCreateModel):
            return True

        return self.to_dict() != other.to_dict()
