# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class QualerApiModelsAssetReservationToAssetReservationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'original_begin_date': 'datetime',
        'original_end_date': 'datetime',
        'begin_date': 'datetime',
        'end_date': 'datetime',
        'reserved_on': 'datetime',
        'reserved_on_utc': 'datetime',
        'comments': 'str',
        'product_id': 'int',
        'asset_id': 'int',
        'service_order_id': 'int',
        'reserved_by_id': 'int',
        'reserved_by_name': 'str'
    }

    attribute_map = {
        'original_begin_date': 'OriginalBeginDate',
        'original_end_date': 'OriginalEndDate',
        'begin_date': 'BeginDate',
        'end_date': 'EndDate',
        'reserved_on': 'ReservedOn',
        'reserved_on_utc': 'ReservedOnUtc',
        'comments': 'Comments',
        'product_id': 'ProductId',
        'asset_id': 'AssetId',
        'service_order_id': 'ServiceOrderId',
        'reserved_by_id': 'ReservedById',
        'reserved_by_name': 'ReservedByName'
    }

    def __init__(self, original_begin_date=None, original_end_date=None, begin_date=None, end_date=None, reserved_on=None, reserved_on_utc=None, comments=None, product_id=None, asset_id=None, service_order_id=None, reserved_by_id=None, reserved_by_name=None, _configuration=None):  # noqa: E501
        """QualerApiModelsAssetReservationToAssetReservationResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._original_begin_date = None
        self._original_end_date = None
        self._begin_date = None
        self._end_date = None
        self._reserved_on = None
        self._reserved_on_utc = None
        self._comments = None
        self._product_id = None
        self._asset_id = None
        self._service_order_id = None
        self._reserved_by_id = None
        self._reserved_by_name = None
        self.discriminator = None

        if original_begin_date is not None:
            self.original_begin_date = original_begin_date
        if original_end_date is not None:
            self.original_end_date = original_end_date
        if begin_date is not None:
            self.begin_date = begin_date
        if end_date is not None:
            self.end_date = end_date
        if reserved_on is not None:
            self.reserved_on = reserved_on
        if reserved_on_utc is not None:
            self.reserved_on_utc = reserved_on_utc
        if comments is not None:
            self.comments = comments
        if product_id is not None:
            self.product_id = product_id
        if asset_id is not None:
            self.asset_id = asset_id
        if service_order_id is not None:
            self.service_order_id = service_order_id
        if reserved_by_id is not None:
            self.reserved_by_id = reserved_by_id
        if reserved_by_name is not None:
            self.reserved_by_name = reserved_by_name

    @property
    def original_begin_date(self):
        """Gets the original_begin_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The original_begin_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._original_begin_date

    @original_begin_date.setter
    def original_begin_date(self, original_begin_date):
        """Sets the original_begin_date of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param original_begin_date: The original_begin_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: datetime
        """

        self._original_begin_date = original_begin_date

    @property
    def original_end_date(self):
        """Gets the original_end_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The original_end_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._original_end_date

    @original_end_date.setter
    def original_end_date(self, original_end_date):
        """Sets the original_end_date of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param original_end_date: The original_end_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: datetime
        """

        self._original_end_date = original_end_date

    @property
    def begin_date(self):
        """Gets the begin_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The begin_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._begin_date

    @begin_date.setter
    def begin_date(self, begin_date):
        """Sets the begin_date of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param begin_date: The begin_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: datetime
        """

        self._begin_date = begin_date

    @property
    def end_date(self):
        """Gets the end_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The end_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param end_date: The end_date of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: datetime
        """

        self._end_date = end_date

    @property
    def reserved_on(self):
        """Gets the reserved_on of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The reserved_on of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._reserved_on

    @reserved_on.setter
    def reserved_on(self, reserved_on):
        """Sets the reserved_on of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param reserved_on: The reserved_on of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: datetime
        """

        self._reserved_on = reserved_on

    @property
    def reserved_on_utc(self):
        """Gets the reserved_on_utc of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The reserved_on_utc of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._reserved_on_utc

    @reserved_on_utc.setter
    def reserved_on_utc(self, reserved_on_utc):
        """Sets the reserved_on_utc of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param reserved_on_utc: The reserved_on_utc of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: datetime
        """

        self._reserved_on_utc = reserved_on_utc

    @property
    def comments(self):
        """Gets the comments of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The comments of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param comments: The comments of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: str
        """

        self._comments = comments

    @property
    def product_id(self):
        """Gets the product_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The product_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: int
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id):
        """Sets the product_id of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param product_id: The product_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: int
        """

        self._product_id = product_id

    @property
    def asset_id(self):
        """Gets the asset_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The asset_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: int
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param asset_id: The asset_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: int
        """

        self._asset_id = asset_id

    @property
    def service_order_id(self):
        """Gets the service_order_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The service_order_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: int
        """
        return self._service_order_id

    @service_order_id.setter
    def service_order_id(self, service_order_id):
        """Sets the service_order_id of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param service_order_id: The service_order_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: int
        """

        self._service_order_id = service_order_id

    @property
    def reserved_by_id(self):
        """Gets the reserved_by_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The reserved_by_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: int
        """
        return self._reserved_by_id

    @reserved_by_id.setter
    def reserved_by_id(self, reserved_by_id):
        """Sets the reserved_by_id of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param reserved_by_id: The reserved_by_id of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: int
        """

        self._reserved_by_id = reserved_by_id

    @property
    def reserved_by_name(self):
        """Gets the reserved_by_name of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501


        :return: The reserved_by_name of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :rtype: str
        """
        return self._reserved_by_name

    @reserved_by_name.setter
    def reserved_by_name(self, reserved_by_name):
        """Sets the reserved_by_name of this QualerApiModelsAssetReservationToAssetReservationResponse.


        :param reserved_by_name: The reserved_by_name of this QualerApiModelsAssetReservationToAssetReservationResponse.  # noqa: E501
        :type: str
        """

        self._reserved_by_name = reserved_by_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QualerApiModelsAssetReservationToAssetReservationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QualerApiModelsAssetReservationToAssetReservationResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, QualerApiModelsAssetReservationToAssetReservationResponse):
            return True

        return self.to_dict() != other.to_dict()
