# coding: utf-8

"""
    Qualer.Web.Mvc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class QualerApiModelsClientsFromSponsoredEmployeeModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_company_id': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'login_email': 'str',
        'password': 'str',
        'subscription_email': 'str',
        'mobile_phone': 'str',
        'office_phone': 'str'
    }

    attribute_map = {
        'client_company_id': 'ClientCompanyId',
        'first_name': 'FirstName',
        'last_name': 'LastName',
        'login_email': 'LoginEmail',
        'password': 'Password',
        'subscription_email': 'SubscriptionEmail',
        'mobile_phone': 'MobilePhone',
        'office_phone': 'OfficePhone'
    }

    def __init__(self, client_company_id=None, first_name=None, last_name=None, login_email=None, password=None, subscription_email=None, mobile_phone=None, office_phone=None, _configuration=None):  # noqa: E501
        """QualerApiModelsClientsFromSponsoredEmployeeModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._client_company_id = None
        self._first_name = None
        self._last_name = None
        self._login_email = None
        self._password = None
        self._subscription_email = None
        self._mobile_phone = None
        self._office_phone = None
        self.discriminator = None

        if client_company_id is not None:
            self.client_company_id = client_company_id
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if login_email is not None:
            self.login_email = login_email
        if password is not None:
            self.password = password
        if subscription_email is not None:
            self.subscription_email = subscription_email
        if mobile_phone is not None:
            self.mobile_phone = mobile_phone
        if office_phone is not None:
            self.office_phone = office_phone

    @property
    def client_company_id(self):
        """Gets the client_company_id of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501


        :return: The client_company_id of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :rtype: int
        """
        return self._client_company_id

    @client_company_id.setter
    def client_company_id(self, client_company_id):
        """Sets the client_company_id of this QualerApiModelsClientsFromSponsoredEmployeeModel.


        :param client_company_id: The client_company_id of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :type: int
        """

        self._client_company_id = client_company_id

    @property
    def first_name(self):
        """Gets the first_name of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501


        :return: The first_name of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this QualerApiModelsClientsFromSponsoredEmployeeModel.


        :param first_name: The first_name of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501


        :return: The last_name of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this QualerApiModelsClientsFromSponsoredEmployeeModel.


        :param last_name: The last_name of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def login_email(self):
        """Gets the login_email of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501


        :return: The login_email of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :rtype: str
        """
        return self._login_email

    @login_email.setter
    def login_email(self, login_email):
        """Sets the login_email of this QualerApiModelsClientsFromSponsoredEmployeeModel.


        :param login_email: The login_email of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :type: str
        """

        self._login_email = login_email

    @property
    def password(self):
        """Gets the password of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501


        :return: The password of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this QualerApiModelsClientsFromSponsoredEmployeeModel.


        :param password: The password of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def subscription_email(self):
        """Gets the subscription_email of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501


        :return: The subscription_email of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :rtype: str
        """
        return self._subscription_email

    @subscription_email.setter
    def subscription_email(self, subscription_email):
        """Sets the subscription_email of this QualerApiModelsClientsFromSponsoredEmployeeModel.


        :param subscription_email: The subscription_email of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :type: str
        """

        self._subscription_email = subscription_email

    @property
    def mobile_phone(self):
        """Gets the mobile_phone of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501


        :return: The mobile_phone of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :rtype: str
        """
        return self._mobile_phone

    @mobile_phone.setter
    def mobile_phone(self, mobile_phone):
        """Sets the mobile_phone of this QualerApiModelsClientsFromSponsoredEmployeeModel.


        :param mobile_phone: The mobile_phone of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :type: str
        """

        self._mobile_phone = mobile_phone

    @property
    def office_phone(self):
        """Gets the office_phone of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501


        :return: The office_phone of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :rtype: str
        """
        return self._office_phone

    @office_phone.setter
    def office_phone(self, office_phone):
        """Sets the office_phone of this QualerApiModelsClientsFromSponsoredEmployeeModel.


        :param office_phone: The office_phone of this QualerApiModelsClientsFromSponsoredEmployeeModel.  # noqa: E501
        :type: str
        """

        self._office_phone = office_phone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QualerApiModelsClientsFromSponsoredEmployeeModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QualerApiModelsClientsFromSponsoredEmployeeModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, QualerApiModelsClientsFromSponsoredEmployeeModel):
            return True

        return self.to_dict() != other.to_dict()
