# coding: utf-8

# flake8: noqa

"""
Qualer SDK Model Classes

This module provides access to all model classes.
Generated by OpenAPI Generator (https://openapi-generator.tech)

The version of the OpenAPI document: v1
"""

from __future__ import annotations

import importlib
import re
from pathlib import Path
from typing import Any, Dict, Set, Tuple

# --- discovery (non-deprecated) ------------------------------------------------

_THIS_DIR = Path(__file__).resolve().parent
_DEPRECATED_PKG_NAME = __name__ + ".deprecated"

# Cache: symbol -> module_name (relative to qualer_sdk.models)
_NAME_TO_MODULE: Dict[str, str] = {}
_ALL: Set[str] = set()

# Conservative class-name scan:
# - Captures "class Foo:" and "class Foo(...):"
# - We map every class defined in the module.
_CLASS_RE = re.compile(r"^\s*class\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.M)


def _discover_models() -> None:
    if _NAME_TO_MODULE:
        return

    for py in _THIS_DIR.glob("*.py"):
        if py.name == "__init__.py":
            continue

        text = py.read_text(encoding="utf-8", errors="replace")

        # If a model file itself is deprecated, it should be moved to ./deprecated/.
        # Still, as a safety net: don’t auto-register anything that contains DeprecationWarning.
        if "DeprecationWarning" in text:
            continue

        module_name = py.stem
        for cls in _CLASS_RE.findall(text):
            # Avoid clobbering in rare collisions; first wins.
            _NAME_TO_MODULE.setdefault(cls, module_name)
            _ALL.add(cls)

    # Also include whatever the deprecated package advertises (but don’t import its modules)
    try:
        deprecated = importlib.import_module(_DEPRECATED_PKG_NAME)
        for name in getattr(deprecated, "__all__", []):
            _ALL.add(name)
    except Exception:
        # If deprecated package doesn’t exist yet, that’s fine.
        pass


def __getattr__(name: str) -> Any:
    _discover_models()

    # First: non-deprecated models
    mod = _NAME_TO_MODULE.get(name)
    if mod is not None:
        m = importlib.import_module(f".{mod}", __name__)
        try:
            return getattr(m, name)
        except AttributeError:
            # The scan said it exists, but module didn't provide it; treat as missing.
            raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    # Second: deprecated models (warn-on-access is handled in deprecated/__init__.py)
    try:
        deprecated = importlib.import_module(_DEPRECATED_PKG_NAME)
        return getattr(deprecated, name)
    except AttributeError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    _discover_models()
    return sorted(set(globals().keys()) | _ALL)


# Expose everything for `from qualer_sdk.models import *`.
# This will call __getattr__ for each item during import-star.
_discover_models()
__all__ = sorted(_ALL)  # pyright: ignore[reportUnsupportedDunderAll]
