# coding: utf-8

"""
Qualer.Web.Mvc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist


class QualerApiModelsAssetToEmployeePreferenceResponseModel(BaseModel):
    """
    QualerApiModelsAssetToEmployeePreferenceResponseModel
    """

    element_type: Optional[StrictStr] = Field(None, alias="ElementType")
    element_page: Optional[StrictStr] = Field(None, alias="ElementPage")
    element_id: Optional[StrictStr] = Field(None, alias="ElementId")
    preference: Optional[conlist(StrictStr)] = Field(None, alias="Preference")
    is_pinned: Optional[StrictBool] = Field(None, alias="IsPinned")
    __properties = ["ElementType", "ElementPage", "ElementId", "Preference", "IsPinned"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(
        cls, json_str: str
    ) -> QualerApiModelsAssetToEmployeePreferenceResponseModel:
        """Create an instance of QualerApiModelsAssetToEmployeePreferenceResponseModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(
        cls, obj: dict
    ) -> QualerApiModelsAssetToEmployeePreferenceResponseModel:
        """Create an instance of QualerApiModelsAssetToEmployeePreferenceResponseModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QualerApiModelsAssetToEmployeePreferenceResponseModel.parse_obj(obj)

        _obj = QualerApiModelsAssetToEmployeePreferenceResponseModel.parse_obj(
            {
                "element_type": obj.get("ElementType"),
                "element_page": obj.get("ElementPage"),
                "element_id": obj.get("ElementId"),
                "preference": obj.get("Preference"),
                "is_pinned": obj.get("IsPinned"),
            }
        )
        return _obj
